#include <QSqlQuery>
#include <QSqlRecord>
#include <QDate>
#include <QDateTime>
#include <QtCharts/QChart>
#include <QtCharts/QPieSeries>
#include <QtCharts/QPieSlice>
#include <QEasingCurve>
#include <QTimer>
#include <QBrush>
#include <QPrinter>
#include <QPainter>
#include <QFileDialog>
#include <QTextDocument>
#include <QHeaderView>
#include <QLocale>
#include <QRegularExpression>
#include <algorithm>
#include <utility>
#include <QPalette>
#include <QSpinBox>
#include <QDoubleSpinBox>
#include <QGraphicsDropShadowEffect>
#include <QToolTip>
#include <QGridLayout>
#include <QGraphicsLayout>
#include <QCursor>
#include <QRegularExpression>
#include <QRegularExpressionValidator>
#include <QFileDialog>
#include <QTextStream>
#include <QStringConverter>
#include <QRandomGenerator>
#include <QIcon>
#include <QDebug>
#include <QMediaPlayer>
#include <QAudioOutput>
#include <QDialog>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QDir>
#include <QFileInfo>
#include <QInputDialog>
#include <QSettings>
#include <QProcess>
#include <QStandardPaths>
#include <QVector>
#include <QHash>
#include <limits>
#include <cmath>
#include <QCamera>
#include <QMediaCaptureSession>
#include <QImageCapture>
#include <QMediaDevices>
#include <QVideoWidget>
#include <QSerialPort>
#include <QSerialPortInfo>
#include <QNetworkAccessManager>
#include <QNetworkRequest>
#include <QNetworkReply>
#include <QEventLoop>
#include <QCoreApplication>
#include <QSlider>
#include <QLineEdit>
#include <QHeaderView>
#include <QRegularExpression>
#include <QSqlDatabase>
#include <QSqlQuery>
#include <QSqlError>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QLabel>
#include <QTimer>
#include <QLayout>
#include <QFile>
#include <QDir>
#include <QFileInfo>
#include <QDateTime>
#include <QTextStream>
#include <QTableWidget>
#include <QTextEdit>
#include <QPlainTextEdit>
#include <QLineEdit>
#include <QPushButton>
#include <QProcess>
#include <QProcessEnvironment>
#include <QCoreApplication>
#include <QFileDialog>
#include <QTextDocument>
#include <QPrinter>
#include <QTime>
#include <cmath>
#include <QtCharts/QLegend>
#include <QtCharts/QBarSeries>
#include <QtCharts/QBarSet>
#include <QtCharts/QBarCategoryAxis>
#include <QtCharts/QValueAxis>
#include <QtCharts/QLineSeries>
#include <QtCharts/QDateTimeAxis>