--------------------------------------------------------
--  Fichier créé - jeudi-mars-05-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BATEAU
--------------------------------------------------------

  CREATE TABLE "PROJET"."BATEAU" 
   (	"ID_BATEAU" NUMBER, 
	"NOM" VARCHAR2(100 BYTE), 
	"TYPE" VARCHAR2(30 BYTE), 
	"IMMATRICULATION" VARCHAR2(50 BYTE), 
	"PUISSANCE_MOTEUR" VARCHAR2(50 BYTE), 
	"PROPRIETAIRE" VARCHAR2(100 BYTE), 
	"STATUT" VARCHAR2(20 BYTE), 
	"NUMERO_LICENSE" VARCHAR2(50 BYTE), 
	"DATE_EXPIRATION_LICENCE" DATE, 
	"QUAI_ID" NUMBER, 
	"ID_PECHEUR" NUMBER, 
	"ASSURANCE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHARGER
--------------------------------------------------------

  CREATE TABLE "PROJET"."CHARGER" 
   (	"ID_BATEAU" NUMBER, 
	"STOCK_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "PROJET"."EMPLOYE" 
   (	"CIN" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"NOM" VARCHAR2(50 BYTE), 
	"PHOTO" VARCHAR2(255 BYTE), 
	"POSTE" VARCHAR2(50 BYTE), 
	"SERVICE" VARCHAR2(30 BYTE), 
	"DATE_EMBAUCHE" DATE, 
	"STATUT_PROFESSIONNEL" VARCHAR2(20 BYTE), 
	"NUMERO_TELEPHONE" VARCHAR2(20 BYTE), 
	"ADRESSE_EMAIL" VARCHAR2(100 BYTE), 
	"MOT_DE_PASSE" VARCHAR2(255 BYTE), 
	"VILLE" VARCHAR2(50 BYTE), 
	"ADRESSE" VARCHAR2(200 BYTE), 
	"CERTIFICATIONS" VARCHAR2(200 BYTE), 
	"NIVEAU_COMPETENCE" VARCHAR2(30 BYTE), 
	"NUMERO_LICENSE" VARCHAR2(50 BYTE), 
	"DATE_EXPIRATION_CERTIFICATION" DATE, 
	"HORAIRE_TRAVAIL" VARCHAR2(20 BYTE), 
	"AFFECT_DOT_DATE" DATE, 
	"AFFECT_DOT_DEPT" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENT
--------------------------------------------------------

  CREATE TABLE "PROJET"."EQUIPEMENT" 
   (	"ID_EQUIPEMENT" NUMBER, 
	"NOM" VARCHAR2(100 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"ETAT" VARCHAR2(30 BYTE), 
	"DATE_ACQUISITION" DATE, 
	"LOCALISATION" VARCHAR2(50 BYTE), 
	"COUT_ESTIME" NUMBER(12,2), 
	"FOURNISSEUR" VARCHAR2(100 BYTE), 
	"DISPONIBILITE" VARCHAR2(20 BYTE), 
	"ID_BATEAU" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PECHEUR
--------------------------------------------------------

  CREATE TABLE "PROJET"."PECHEUR" 
   (	"ID_PECHEUR" NUMBER, 
	"NOMPRENOM" VARCHAR2(100 BYTE), 
	"ROLE" VARCHAR2(50 BYTE), 
	"CONTACT" VARCHAR2(50 BYTE), 
	"ANNEES_EXPERIENCE" NUMBER, 
	"STATUT" VARCHAR2(20 BYTE), 
	"DATE_LIMITE" DATE, 
	"CIN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table QUAI
--------------------------------------------------------

  CREATE TABLE "PROJET"."QUAI" 
   (	"QUAI_ID" NUMBER, 
	"QUAI_NOM" VARCHAR2(100 BYTE), 
	"QUAI_TYPE" VARCHAR2(50 BYTE), 
	"LONGUEUR" NUMBER(10,2), 
	"PROFONDEUR" NUMBER(10,2), 
	"CAPACITE" NUMBER, 
	"STATUT" VARCHAR2(30 BYTE), 
	"CURRENTUSAGE" NUMBER, 
	"OCCUPANCYRATE" NUMBER(5,2), 
	"PRIORITYLEVEL" VARCHAR2(20 BYTE), 
	"SAFETYLEVEL" VARCHAR2(20 BYTE), 
	"LIGHTINGSTATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STOCK
--------------------------------------------------------

  CREATE TABLE "PROJET"."STOCK" 
   (	"STOCK_ID" NUMBER, 
	"ESPECE" VARCHAR2(100 BYTE), 
	"QUANTITE" NUMBER(12,2), 
	"ETAT" VARCHAR2(20 BYTE), 
	"S_MIN" NUMBER(12,2), 
	"S_MAX" NUMBER(12,2), 
	"DATE_AJOUT" DATE, 
	"CIN_VENT" VARCHAR2(20 BYTE), 
	"N_CMD" VARCHAR2(50 BYTE), 
	"DATE_VENTE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BATEAU_ID
--------------------------------------------------------

   CREATE SEQUENCE  "PROJET"."SEQ_BATEAU_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CHARGER_ID
--------------------------------------------------------

   CREATE SEQUENCE  "PROJET"."SEQ_CHARGER_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_EQUIPEMENT_ID
--------------------------------------------------------

   CREATE SEQUENCE  "PROJET"."SEQ_EQUIPEMENT_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PECHEUR_ID
--------------------------------------------------------

   CREATE SEQUENCE  "PROJET"."SEQ_PECHEUR_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QUAI_ID
--------------------------------------------------------

   CREATE SEQUENCE  "PROJET"."SEQ_QUAI_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_STOCK_ID
--------------------------------------------------------

   CREATE SEQUENCE  "PROJET"."SEQ_STOCK_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into PROJET.BATEAU
SET DEFINE OFF;
Insert into PROJET.BATEAU (ID_BATEAU,NOM,TYPE,IMMATRICULATION,PUISSANCE_MOTEUR,PROPRIETAIRE,STATUT,NUMERO_LICENSE,DATE_EXPIRATION_LICENCE,QUAI_ID,ID_PECHEUR,ASSURANCE) values ('1','Al Amoud','Chalutier','IM12345','500 CV','Société de Pêche ABC','Actif','LICB001',to_date('30/06/25','DD/MM/RR'),'1','1',to_date('01/01/25','DD/MM/RR'));
Insert into PROJET.BATEAU (ID_BATEAU,NOM,TYPE,IMMATRICULATION,PUISSANCE_MOTEUR,PROPRIETAIRE,STATUT,NUMERO_LICENSE,DATE_EXPIRATION_LICENCE,QUAI_ID,ID_PECHEUR,ASSURANCE) values ('2','La Gazelle','Sardinier','IM12346','350 CV','Pêcheurs Réunis','Actif','LICB002',to_date('31/12/24','DD/MM/RR'),'2','2',to_date('15/06/24','DD/MM/RR'));
Insert into PROJET.BATEAU (ID_BATEAU,NOM,TYPE,IMMATRICULATION,PUISSANCE_MOTEUR,PROPRIETAIRE,STATUT,NUMERO_LICENSE,DATE_EXPIRATION_LICENCE,QUAI_ID,ID_PECHEUR,ASSURANCE) values ('3','Le Dauphin','Palangrier','IM12347','400 CV','Coopérative Maritime','En maintenance','LICB003',to_date('30/09/24','DD/MM/RR'),'3','3',to_date('20/03/24','DD/MM/RR'));
Insert into PROJET.BATEAU (ID_BATEAU,NOM,TYPE,IMMATRICULATION,PUISSANCE_MOTEUR,PROPRIETAIRE,STATUT,NUMERO_LICENSE,DATE_EXPIRATION_LICENCE,QUAI_ID,ID_PECHEUR,ASSURANCE) values ('4','L''Écume','Chalutier','IM12348','600 CV','Armement Maritime SARL','Actif','LICB004',to_date('31/03/25','DD/MM/RR'),'4','4',to_date('10/09/24','DD/MM/RR'));
Insert into PROJET.BATEAU (ID_BATEAU,NOM,TYPE,IMMATRICULATION,PUISSANCE_MOTEUR,PROPRIETAIRE,STATUT,NUMERO_LICENSE,DATE_EXPIRATION_LICENCE,QUAI_ID,ID_PECHEUR,ASSURANCE) values ('5','Le Corsaire','Caseyeur','IM12349','300 CV','Entreprise de Pêche Moderne','Actif','LICB005',to_date('15/08/24','DD/MM/RR'),'5','5',to_date('28/02/24','DD/MM/RR'));
REM INSERTING into PROJET.CHARGER
SET DEFINE OFF;
Insert into PROJET.CHARGER (ID_BATEAU,STOCK_ID) values ('1','1');
Insert into PROJET.CHARGER (ID_BATEAU,STOCK_ID) values ('1','2');
Insert into PROJET.CHARGER (ID_BATEAU,STOCK_ID) values ('2','3');
Insert into PROJET.CHARGER (ID_BATEAU,STOCK_ID) values ('3','4');
Insert into PROJET.CHARGER (ID_BATEAU,STOCK_ID) values ('4','5');
REM INSERTING into PROJET.EMPLOYE
SET DEFINE OFF;
Insert into PROJET.EMPLOYE (CIN,PRENOM,NOM,PHOTO,POSTE,SERVICE,DATE_EMBAUCHE,STATUT_PROFESSIONNEL,NUMERO_TELEPHONE,ADRESSE_EMAIL,MOT_DE_PASSE,VILLE,ADRESSE,CERTIFICATIONS,NIVEAU_COMPETENCE,NUMERO_LICENSE,DATE_EXPIRATION_CERTIFICATION,HORAIRE_TRAVAIL,AFFECT_DOT_DATE,AFFECT_DOT_DEPT) values ('12345678','hamzaaaaaaaaaa','saidaneaaaaaaaa',null,'Capitaine','Port',to_date('15/01/20','DD/MM/RR'),'Actif','0612345678','saidanehamza87@gmail.com','000000','Tunis','12 Rue de la Mer','Capitaine 200 tonnes','Débutant','LIC001',to_date('31/12/26','DD/MM/RR'),'Matin',to_date('01/01/23','DD/MM/RR'),'Flotte A');
Insert into PROJET.EMPLOYE (CIN,PRENOM,NOM,PHOTO,POSTE,SERVICE,DATE_EMBAUCHE,STATUT_PROFESSIONNEL,NUMERO_TELEPHONE,ADRESSE_EMAIL,MOT_DE_PASSE,VILLE,ADRESSE,CERTIFICATIONS,NIVEAU_COMPETENCE,NUMERO_LICENSE,DATE_EXPIRATION_CERTIFICATION,HORAIRE_TRAVAIL,AFFECT_DOT_DATE,AFFECT_DOT_DEPT) values ('55555555','Fatima','Zahra','/photos/fatima.jpg','Mécanicien','Maintenance',to_date('20/03/21','DD/MM/RR'),'Inactif','0623456789','fatima.zahra@email.com','pass456','Tunis','34 Avenue des Pêcheurs','Mécanique marine','Avancé','LIC002',to_date('30/06/27','DD/MM/RR'),'Matin',to_date('15/02/23','DD/MM/RR'),'Maintenance');
Insert into PROJET.EMPLOYE (CIN,PRENOM,NOM,PHOTO,POSTE,SERVICE,DATE_EMBAUCHE,STATUT_PROFESSIONNEL,NUMERO_TELEPHONE,ADRESSE_EMAIL,MOT_DE_PASSE,VILLE,ADRESSE,CERTIFICATIONS,NIVEAU_COMPETENCE,NUMERO_LICENSE,DATE_EXPIRATION_CERTIFICATION,HORAIRE_TRAVAIL,AFFECT_DOT_DATE,AFFECT_DOT_DEPT) values ('CIN003','Youssef','El Mansouri','/photos/youssef.jpg','Matelot','Navigation',to_date('10/06/22','DD/MM/RR'),'Actif','0634567890','youssef.elm@email.com','pass789','Agadir','56 Rue du Port','Matelotage','Intermédiaire','LIC003',to_date('15/03/24','DD/MM/RR'),'Temps partiel',to_date('10/03/23','DD/MM/RR'),'Flotte B');
Insert into PROJET.EMPLOYE (CIN,PRENOM,NOM,PHOTO,POSTE,SERVICE,DATE_EMBAUCHE,STATUT_PROFESSIONNEL,NUMERO_TELEPHONE,ADRESSE_EMAIL,MOT_DE_PASSE,VILLE,ADRESSE,CERTIFICATIONS,NIVEAU_COMPETENCE,NUMERO_LICENSE,DATE_EXPIRATION_CERTIFICATION,HORAIRE_TRAVAIL,AFFECT_DOT_DATE,AFFECT_DOT_DEPT) values ('13222222','Karim','Idrissi','/photos/karim.jpg','Mécanicien','Sécurité',to_date('05/11/19','DD/MM/RR'),'Inactif','0645678901','karim.idrissi@email.com','passabc','Tunis','89 Rue du Commerce','Sécurité','Intermédiaire','LIC004',to_date('30/09/28','DD/MM/RR'),'Matin',to_date('20/01/23','DD/MM/RR'),'Logistique');
REM INSERTING into PROJET.EQUIPEMENT
SET DEFINE OFF;
Insert into PROJET.EQUIPEMENT (ID_EQUIPEMENT,NOM,TYPE,ETAT,DATE_ACQUISITION,LOCALISATION,COUT_ESTIME,FOURNISSEUR,DISPONIBILITE,ID_BATEAU) values ('1','Filet de pêche','Filet','Bon',to_date('10/05/23','DD/MM/RR'),'Bateau 1','15000','Equipement Maritime SARL','Disponible','1');
Insert into PROJET.EQUIPEMENT (ID_EQUIPEMENT,NOM,TYPE,ETAT,DATE_ACQUISITION,LOCALISATION,COUT_ESTIME,FOURNISSEUR,DISPONIBILITE,ID_BATEAU) values ('2','Sonar','Électronique','Excellent',to_date('22/08/23','DD/MM/RR'),'Bateau 2','25000','Marine Tech','Disponible','2');
Insert into PROJET.EQUIPEMENT (ID_EQUIPEMENT,NOM,TYPE,ETAT,DATE_ACQUISITION,LOCALISATION,COUT_ESTIME,FOURNISSEUR,DISPONIBILITE,ID_BATEAU) values ('3','Moteur hors-bord','Moteur','À réviser',to_date('05/11/22','DD/MM/RR'),'Atelier','45000','Moteurs Maroc','En maintenance','3');
Insert into PROJET.EQUIPEMENT (ID_EQUIPEMENT,NOM,TYPE,ETAT,DATE_ACQUISITION,LOCALISATION,COUT_ESTIME,FOURNISSEUR,DISPONIBILITE,ID_BATEAU) values ('4','Treuil','Mécanique','Bon',to_date('15/03/23','DD/MM/RR'),'Bateau 4','18500','Equipement Maritime SARL','Disponible','4');
Insert into PROJET.EQUIPEMENT (ID_EQUIPEMENT,NOM,TYPE,ETAT,DATE_ACQUISITION,LOCALISATION,COUT_ESTIME,FOURNISSEUR,DISPONIBILITE,ID_BATEAU) values ('5','GPS','Électronique','Excellent',to_date('30/09/23','DD/MM/RR'),'Bateau 5','12000','Marine Tech','Disponible','5');
REM INSERTING into PROJET.PECHEUR
SET DEFINE OFF;
Insert into PROJET.PECHEUR (ID_PECHEUR,NOMPRENOM,ROLE,CONTACT,ANNEES_EXPERIENCE,STATUT,DATE_LIMITE,CIN) values ('1','Hassanaaaaaaa El Fassi','Capitaine',null,'15','Inactif',to_date('05/03/26','DD/MM/RR'),'12345678');
Insert into PROJET.PECHEUR (ID_PECHEUR,NOMPRENOM,ROLE,CONTACT,ANNEES_EXPERIENCE,STATUT,DATE_LIMITE,CIN) values ('2','Rachid Alami','Matelot','0622334455','5','Actif',to_date('30/06/24','DD/MM/RR'),'CIN003');
Insert into PROJET.PECHEUR (ID_PECHEUR,NOMPRENOM,ROLE,CONTACT,ANNEES_EXPERIENCE,STATUT,DATE_LIMITE,CIN) values ('3','Mohamed Benbrahim','Mécanicien','0633445566','8','Actif',to_date('15/03/25','DD/MM/RR'),'55555555');
Insert into PROJET.PECHEUR (ID_PECHEUR,NOMPRENOM,ROLE,CONTACT,ANNEES_EXPERIENCE,STATUT,DATE_LIMITE,CIN) values ('4','Said Chaoui','Second','0644556677','10','Actif',to_date('30/09/24','DD/MM/RR'),'13222222');
Insert into PROJET.PECHEUR (ID_PECHEUR,NOMPRENOM,ROLE,CONTACT,ANNEES_EXPERIENCE,STATUT,DATE_LIMITE,CIN) values ('5','Hamid Tazi','Matelot','0655667788','3','Actif',to_date('20/12/24','DD/MM/RR'),null);
REM INSERTING into PROJET.QUAI
SET DEFINE OFF;
Insert into PROJET.QUAI (QUAI_ID,QUAI_NOM,QUAI_TYPE,LONGUEUR,PROFONDEUR,CAPACITE,STATUT,CURRENTUSAGE,OCCUPANCYRATE,PRIORITYLEVEL,SAFETYLEVEL,LIGHTINGSTATUS) values ('1','Quai A','Pêche','120,5','8,5','10','Actif','3','30','Haute','A','Fonctionnel');
Insert into PROJET.QUAI (QUAI_ID,QUAI_NOM,QUAI_TYPE,LONGUEUR,PROFONDEUR,CAPACITE,STATUT,CURRENTUSAGE,OCCUPANCYRATE,PRIORITYLEVEL,SAFETYLEVEL,LIGHTINGSTATUS) values ('2','Quai B','Pêche','150','9','15','Actif','5','33,33','Moyenne','B','Fonctionnel');
Insert into PROJET.QUAI (QUAI_ID,QUAI_NOM,QUAI_TYPE,LONGUEUR,PROFONDEUR,CAPACITE,STATUT,CURRENTUSAGE,OCCUPANCYRATE,PRIORITYLEVEL,SAFETYLEVEL,LIGHTINGSTATUS) values ('3','Quai C','Maintenance','80,75','6,5','5','En maintenance','1','20','Basse','C','En panne');
Insert into PROJET.QUAI (QUAI_ID,QUAI_NOM,QUAI_TYPE,LONGUEUR,PROFONDEUR,CAPACITE,STATUT,CURRENTUSAGE,OCCUPANCYRATE,PRIORITYLEVEL,SAFETYLEVEL,LIGHTINGSTATUS) values ('4','Quai D','Pêche','200','10','20','Actif','8','40','Haute','A','Fonctionnel');
Insert into PROJET.QUAI (QUAI_ID,QUAI_NOM,QUAI_TYPE,LONGUEUR,PROFONDEUR,CAPACITE,STATUT,CURRENTUSAGE,OCCUPANCYRATE,PRIORITYLEVEL,SAFETYLEVEL,LIGHTINGSTATUS) values ('5','Quai E','Commerce','180,25','9,5','12','Actif','4','33,33','Moyenne','B','Fonctionnel');
REM INSERTING into PROJET.STOCK
SET DEFINE OFF;
Insert into PROJET.STOCK (STOCK_ID,ESPECE,QUANTITE,ETAT,S_MIN,S_MAX,DATE_AJOUT,CIN_VENT,N_CMD,DATE_VENTE) values ('1','Sardine','5000','Frais','1000','10000',to_date('15/01/24','DD/MM/RR'),null,null,null);
Insert into PROJET.STOCK (STOCK_ID,ESPECE,QUANTITE,ETAT,S_MIN,S_MAX,DATE_AJOUT,CIN_VENT,N_CMD,DATE_VENTE) values ('2','Maquereau','3500,5','Frais','800','8000',to_date('16/01/24','DD/MM/RR'),null,null,null);
Insert into PROJET.STOCK (STOCK_ID,ESPECE,QUANTITE,ETAT,S_MIN,S_MAX,DATE_AJOUT,CIN_VENT,N_CMD,DATE_VENTE) values ('3','Thon','1200,75','Congelé','500','5000',to_date('14/01/24','DD/MM/RR'),'CIN002','CMD001',to_date('17/01/24','DD/MM/RR'));
Insert into PROJET.STOCK (STOCK_ID,ESPECE,QUANTITE,ETAT,S_MIN,S_MAX,DATE_AJOUT,CIN_VENT,N_CMD,DATE_VENTE) values ('4','Merlu','2800,25','Frais','600','6000',to_date('13/01/24','DD/MM/RR'),null,null,null);
Insert into PROJET.STOCK (STOCK_ID,ESPECE,QUANTITE,ETAT,S_MIN,S_MAX,DATE_AJOUT,CIN_VENT,N_CMD,DATE_VENTE) values ('5','Crevette','800','Congelé','200','2000',to_date('12/01/24','DD/MM/RR'),'CIN004','CMD002',to_date('16/01/24','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index SYS_C007498
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET"."SYS_C007498" ON "PROJET"."BATEAU" ("ID_BATEAU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007499
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET"."SYS_C007499" ON "PROJET"."CHARGER" ("ID_BATEAU", "STOCK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007500
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET"."SYS_C007500" ON "PROJET"."EMPLOYE" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007501
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET"."SYS_C007501" ON "PROJET"."EQUIPEMENT" ("ID_EQUIPEMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007502
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET"."SYS_C007502" ON "PROJET"."PECHEUR" ("ID_PECHEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007503
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET"."SYS_C007503" ON "PROJET"."QUAI" ("QUAI_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007504
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET"."SYS_C007504" ON "PROJET"."STOCK" ("STOCK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BATEAU
--------------------------------------------------------

  ALTER TABLE "PROJET"."BATEAU" ADD PRIMARY KEY ("ID_BATEAU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CHARGER
--------------------------------------------------------

  ALTER TABLE "PROJET"."CHARGER" ADD PRIMARY KEY ("ID_BATEAU", "STOCK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "PROJET"."EMPLOYE" ADD PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EQUIPEMENT
--------------------------------------------------------

  ALTER TABLE "PROJET"."EQUIPEMENT" ADD PRIMARY KEY ("ID_EQUIPEMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PECHEUR
--------------------------------------------------------

  ALTER TABLE "PROJET"."PECHEUR" ADD PRIMARY KEY ("ID_PECHEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QUAI
--------------------------------------------------------

  ALTER TABLE "PROJET"."QUAI" ADD PRIMARY KEY ("QUAI_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STOCK
--------------------------------------------------------

  ALTER TABLE "PROJET"."STOCK" ADD PRIMARY KEY ("STOCK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BATEAU
--------------------------------------------------------

  ALTER TABLE "PROJET"."BATEAU" ADD CONSTRAINT "FK_BATEAU_PECHEUR" FOREIGN KEY ("ID_PECHEUR")
	  REFERENCES "PROJET"."PECHEUR" ("ID_PECHEUR") ENABLE;
  ALTER TABLE "PROJET"."BATEAU" ADD CONSTRAINT "FK_BATEAU_QUAI" FOREIGN KEY ("QUAI_ID")
	  REFERENCES "PROJET"."QUAI" ("QUAI_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHARGER
--------------------------------------------------------

  ALTER TABLE "PROJET"."CHARGER" ADD CONSTRAINT "FK_CHARGER_BATEAU" FOREIGN KEY ("ID_BATEAU")
	  REFERENCES "PROJET"."BATEAU" ("ID_BATEAU") ENABLE;
  ALTER TABLE "PROJET"."CHARGER" ADD CONSTRAINT "FK_CHARGER_STOCK" FOREIGN KEY ("STOCK_ID")
	  REFERENCES "PROJET"."STOCK" ("STOCK_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIPEMENT
--------------------------------------------------------

  ALTER TABLE "PROJET"."EQUIPEMENT" ADD CONSTRAINT "FK_EQUIPEMENT_BATEAU" FOREIGN KEY ("ID_BATEAU")
	  REFERENCES "PROJET"."BATEAU" ("ID_BATEAU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PECHEUR
--------------------------------------------------------

  ALTER TABLE "PROJET"."PECHEUR" ADD CONSTRAINT "FK_PECHEUR_EMPLOYE" FOREIGN KEY ("CIN")
	  REFERENCES "PROJET"."EMPLOYE" ("CIN") ENABLE;