--------------------------------------------------------
--  File created - Friday-February-27-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BATEAU
--------------------------------------------------------

  CREATE TABLE "PROJET"."BATEAU" 
   (	"ID_BATEAU" NUMBER, 
	"NOM" VARCHAR2(100 BYTE), 
	"TYPE" VARCHAR2(30 BYTE), 
	"IMMATRICULATION" VARCHAR2(50 BYTE), 
	"PUISSANCE_MOTEUR" VARCHAR2(50 BYTE), 
	"PROPRIETAIRE" VARCHAR2(100 BYTE), 
	"STATUT" VARCHAR2(20 BYTE), 
	"NUMERO_LICENSE" VARCHAR2(50 BYTE), 
	"DATE_EXPIRATION_LICENCE" DATE, 
	"QUAI_ID" NUMBER, 
	"ID_PECHEUR" NUMBER, 
	"ASSURANCE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHARGER
--------------------------------------------------------

  CREATE TABLE "PROJET"."CHARGER" 
   (	"ID_BATEAU" NUMBER, 
	"STOCK_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "PROJET"."EMPLOYE" 
   (	"CIN" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"NOM" VARCHAR2(50 BYTE), 
	"PHOTO" VARCHAR2(255 BYTE), 
	"POSTE" VARCHAR2(50 BYTE), 
	"SERVICE" VARCHAR2(30 BYTE), 
	"DATE_EMBAUCHE" DATE, 
	"STATUT_PROFESSIONNEL" VARCHAR2(20 BYTE), 
	"NUMERO_TELEPHONE" VARCHAR2(20 BYTE), 
	"ADRESSE_EMAIL" VARCHAR2(100 BYTE), 
	"MOT_DE_PASSE" VARCHAR2(255 BYTE), 
	"VILLE" VARCHAR2(50 BYTE), 
	"ADRESSE" VARCHAR2(200 BYTE), 
	"CERTIFICATIONS" VARCHAR2(200 BYTE), 
	"NIVEAU_COMPETENCE" VARCHAR2(30 BYTE), 
	"NUMERO_LICENSE" VARCHAR2(50 BYTE), 
	"DATE_EXPIRATION_CERTIFICATION" DATE, 
	"HORAIRE_TRAVAIL" VARCHAR2(20 BYTE), 
	"AFFECT_DOT_DATE" DATE, 
	"AFFECT_DOT_DEPT" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENT
--------------------------------------------------------

  CREATE TABLE "PROJET"."EQUIPEMENT" 
   (	"ID_EQUIPEMENT" NUMBER, 
	"NOM" VARCHAR2(100 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"ETAT" VARCHAR2(30 BYTE), 
	"DATE_ACQUISITION" DATE, 
	"LOCALISATION" VARCHAR2(50 BYTE), 
	"COUT_ESTIME" NUMBER(12,2), 
	"FOURNISSEUR" VARCHAR2(100 BYTE), 
	"DISPONIBILITE" VARCHAR2(20 BYTE), 
	"ID_BATEAU" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PECHEUR
--------------------------------------------------------

  CREATE TABLE "PROJET"."PECHEUR" 
   (	"ID_PECHEUR" NUMBER, 
	"NOMPRENOM" VARCHAR2(100 BYTE), 
	"ROLE" VARCHAR2(50 BYTE), 
	"CONTACT" VARCHAR2(50 BYTE), 
	"ANNEES_EXPERIENCE" NUMBER, 
	"STATUT" VARCHAR2(20 BYTE), 
	"DATE_LIMITE" DATE, 
	"RFID" VARCHAR2(32 BYTE), 
	"CIN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table QUAI
--------------------------------------------------------

  CREATE TABLE "PROJET"."QUAI" 
   (	"QUAI_ID" NUMBER, 
	"QUAI_NOM" VARCHAR2(100 BYTE), 
	"QUAI_TYPE" VARCHAR2(50 BYTE), 
	"LONGUEUR" NUMBER(10,2), 
	"PROFONDEUR" NUMBER(10,2), 
	"CAPACITE" NUMBER, 
	"STATUT" VARCHAR2(30 BYTE), 
	"CURRENTUSAGE" NUMBER, 
	"OCCUPANCYRATE" NUMBER(5,2), 
	"PRIORITYLEVEL" VARCHAR2(20 BYTE), 
	"SAFETYLEVEL" VARCHAR2(20 BYTE), 
	"LIGHTINGSTATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STOCK
--------------------------------------------------------

  CREATE TABLE "PROJET"."STOCK" 
   (	"STOCK_ID" NUMBER, 
	"ESPECE" VARCHAR2(100 BYTE), 
	"QUANTITE" NUMBER, 
	"ETAT" VARCHAR2(20 BYTE), 
	"S_MIN" NUMBER(12,2), 
	"S_MAX" NUMBER(12,2), 
	"DATE_AJOUT" DATE, 
	"CIN_VENT" VARCHAR2(20 BYTE), 
	"N_CMD" VARCHAR2(50 BYTE), 
	"DATE_VENT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PROJET.BATEAU
SET DEFINE OFF;
REM INSERTING into PROJET.CHARGER
SET DEFINE OFF;
REM INSERTING into PROJET.EMPLOYE
SET DEFINE OFF;
REM INSERTING into PROJET.EQUIPEMENT
SET DEFINE OFF;
REM INSERTING into PROJET.PECHEUR
SET DEFINE OFF;
REM INSERTING into PROJET.QUAI
SET DEFINE OFF;
REM INSERTING into PROJET.STOCK
SET DEFINE OFF;
Insert into PROJET.STOCK (STOCK_ID,ESPECE,QUANTITE,ETAT,S_MIN,S_MAX,DATE_AJOUT,CIN_VENT,N_CMD,DATE_VENT) values ('1','Moule de Mer','100','Frais','50','200',to_date('28/02/26','DD/MM/RR'),'12345678','112',to_date('28/03/26','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index SYS_C007073
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET"."SYS_C007073" ON "PROJET"."BATEAU" ("ID_BATEAU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007074
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET"."SYS_C007074" ON "PROJET"."CHARGER" ("ID_BATEAU", "STOCK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007075
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET"."SYS_C007075" ON "PROJET"."EMPLOYE" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007076
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET"."SYS_C007076" ON "PROJET"."EQUIPEMENT" ("ID_EQUIPEMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007077
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET"."SYS_C007077" ON "PROJET"."PECHEUR" ("ID_PECHEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007078
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET"."SYS_C007078" ON "PROJET"."QUAI" ("QUAI_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007079
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJET"."SYS_C007079" ON "PROJET"."STOCK" ("STOCK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BATEAU
--------------------------------------------------------

  ALTER TABLE "PROJET"."BATEAU" ADD PRIMARY KEY ("ID_BATEAU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CHARGER
--------------------------------------------------------

  ALTER TABLE "PROJET"."CHARGER" ADD PRIMARY KEY ("ID_BATEAU", "STOCK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "PROJET"."EMPLOYE" ADD PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EQUIPEMENT
--------------------------------------------------------

  ALTER TABLE "PROJET"."EQUIPEMENT" ADD PRIMARY KEY ("ID_EQUIPEMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PECHEUR
--------------------------------------------------------

  ALTER TABLE "PROJET"."PECHEUR" ADD PRIMARY KEY ("ID_PECHEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QUAI
--------------------------------------------------------

  ALTER TABLE "PROJET"."QUAI" ADD PRIMARY KEY ("QUAI_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STOCK
--------------------------------------------------------

  ALTER TABLE "PROJET"."STOCK" ADD PRIMARY KEY ("STOCK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BATEAU
--------------------------------------------------------

  ALTER TABLE "PROJET"."BATEAU" ADD CONSTRAINT "FK_BATEAU_PECHEUR" FOREIGN KEY ("ID_PECHEUR")
	  REFERENCES "PROJET"."PECHEUR" ("ID_PECHEUR") ENABLE;
  ALTER TABLE "PROJET"."BATEAU" ADD CONSTRAINT "FK_BATEAU_QUAI" FOREIGN KEY ("QUAI_ID")
	  REFERENCES "PROJET"."QUAI" ("QUAI_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHARGER
--------------------------------------------------------

  ALTER TABLE "PROJET"."CHARGER" ADD CONSTRAINT "FK_CHARGER_BATEAU" FOREIGN KEY ("ID_BATEAU")
	  REFERENCES "PROJET"."BATEAU" ("ID_BATEAU") ENABLE;
  ALTER TABLE "PROJET"."CHARGER" ADD CONSTRAINT "FK_CHARGER_STOCK" FOREIGN KEY ("STOCK_ID")
	  REFERENCES "PROJET"."STOCK" ("STOCK_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIPEMENT
--------------------------------------------------------

  ALTER TABLE "PROJET"."EQUIPEMENT" ADD CONSTRAINT "FK_EQUIPEMENT_BATEAU" FOREIGN KEY ("ID_BATEAU")
	  REFERENCES "PROJET"."BATEAU" ("ID_BATEAU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PECHEUR
--------------------------------------------------------

  ALTER TABLE "PROJET"."PECHEUR" ADD CONSTRAINT "FK_PECHEUR_EMPLOYE" FOREIGN KEY ("CIN")
	  REFERENCES "PROJET"."EMPLOYE" ("CIN") ENABLE;
